[package]
name = "parsimon-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.16"
petgraph = "0.6.0"
serde = { version = "1.0.130", features = ["derive"] }
