[package]
name = "parsimon-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.61"
crossbeam-channel = "0.5.6"
delegate = "0.7.0"
derive-new = "0.5.9"
derive_more = "0.99.17"
itertools = "0.10.3"
ndarray = "0.15.6"
ndarray-stats = "0.5.0"
num_cpus = "1.13.1"
ordered-float = "3.0.0"
petgraph = { version = "0.6.2", features = ["serde-1"] }
rand = "0.8.5"
rayon = "1.5.3"
rustc-hash = "1.1.0"
serde = { version = "1.0.143", features = ["derive"] }
thiserror = "1.0.32"
typed-builder = "0.10.0"

[dev-dependencies]
insta = { version = "1.18.2", features = ["yaml"] }

[features]
