[package]
name = "parsimon-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.48"
delegate = "0.6.1"
derive-new = "0.5.9"
derive_more = "0.99.16"
ordered-float = "2.8.0"
petgraph = { version = "0.6.0", features = ["serde-1"] }
rand = "0.8.4"
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.30"
typed-builder = "0.9.1"

[dev-dependencies]
insta = "1.8.0"
