[package]
name = "parsimon-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.48"
crossbeam-channel = "0.5.1"
delegate = "0.6.1"
derive-new = "0.5.9"
derive_more = "0.99.16"
itertools = "0.10.3"
ndarray = "0.15.4"
ndarray-stats = "0.5.0"
num_cpus = "1.13.1"
ordered-float = "2.8.0"
petgraph = { version = "0.6.0", features = ["serde-1"] }
rand = "0.8.4"
rayon = "1.5.1"
rustc-hash = "1.1.0"
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.30"
typed-builder = "0.9.1"

[dev-dependencies]
insta = "1.8.0"

[features]
