[package]
name = "parsimon-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new = "0.5.9"
derive_more = "0.99.16"
petgraph = "0.6.0"
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.30"

[dev-dependencies]
anyhow = "1.0.44"
insta = "1.8.0"
